### ISSUE TITLE
Crash after STA disconnect in AP+Client mode

### ISSUE THREAD

**Issue by dexterbg** [openvehicles/Open-Vehicle-Monitoring-System-3#45]
We already discussed this on the developer list, it still happens with 3.1.004.

```
I (724433) wifi: bcn_timout,ap_probe_send_start
I (726943) wifi: ap_probe_send over, resett wifi status to disassoc
I (726943) wifi: state: run -> init (1)
I (726943) wifi: n:1 0, o:1 1, ap:1 1, sta:1 0, prof:1
I (726943) netmanager: Interface priority is pp3 (10.170.195.13/255.255.255.255 gateway 10.64.64.64)
I (726953) netmanager: WIFI client down (with MODEM up): reconfigured for MODEM priority
I (726953) time: Network was reconfigured: restarting SNTP client
I (726953) ovms-server-v2: Network was reconfigured: disconnect, and reconnect in 10 seconds
I (726953) ovms-server-v2: Status: Network was reconfigured: disconnect, and reconnect in 10 seconds
I (726963) esp32wifi: STA disconnected with reason 200
I (726963) ovms-server-v2: Status: Disconnected
I (746153) ovms-server-v2: Connection is ovms.dexters-web.de:6867 test1
I (746153) ovms-server-v2: Status: Connecting...Guru Meditation Error: Core  1 panic'ed (StoreProhibited)
. Exception was unhandled.
Core 1 register dump:
PC      : 0x400f7ee6  PS      : 0x00060330  A0      : 0x800f8090  A1      : 0x3ffe8a00 
A2      : 0x3fff55a8  A3      : 0x3fffbb90  A4      : 0x00000001  A5      : 0x00000000 
A6      : 0x00000014  A7      : 0x3ffb10b0  A8      : 0x000000a2  A9      : 0x3ffe89e0 
A10     : 0x3ffe8a00  A11     : 0x00000040  A12     : 0x3f40c298  A13     : 0x081d0000 
A14     : 0x87725000  A15     : 0x00000000  SAR     : 0x00000001  EXCCAUSE: 0x0000001d 
EXCVADDR: 0x0000000a  LBEG    : 0x40145ccc  LEND    : 0x40145ceb  LCOUNT  : 0x00000000 

Backtrace: 0x400f7ee6:0x3ffe8a00 0x400f808d:0x3ffe8a30 0x400f5eff:0x3ffe8a70 0x400f61c6:0x3ffe8aa0 0x400f74b1:0x3ffe8ad0 0x400f775d:0x3ffe8b10
0x400f3f25:0x3ffe8b60 0x400eb47a:0x3ffe8b80 0x400eb4b9:0x3ffe8bd0

#0  0x400f7ee6 in mg_send_dns_query (nc=0x3fff55a8, name=0x3fffbb90 "ovms.dexters-web.de", query_type=1) at
/home/balzer/esp/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/components/mongoose/mongoose/mongoose.c:11172
#1  0x400f8090 in mg_resolve_async_eh (nc=0x3fff55a8, ev=<optimized out>, data=<optimized out>) at
/home/balzer/esp/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/components/mongoose/mongoose/mongoose.c:11629
#2  0x400f5f02 in mg_call (nc=0x3fff55a8, ev_handler=0x400f800c <mg_resolve_async_eh>, user_data=<optimized out>, ev=2, ev_data=0x3ffe8aa0)
    at /home/balzer/esp/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/components/mongoose/mongoose/mongoose.c:2285
#3  0x400f61c9 in mg_if_connect_cb (nc=0x3fff55a8, err=0) at
/home/balzer/esp/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/components/mongoose/mongoose/mongoose.c:2824
#4  0x400f74b4 in mg_mgr_handle_conn (nc=0x3fff55a8, fd_flags=2, now=1522337922.4471409) at
/home/balzer/esp/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/components/mongoose/mongoose/mongoose.c:3705
#5  0x400f7760 in mg_socket_if_poll (iface=<optimized out>, timeout_ms=250) at
/home/balzer/esp/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/components/mongoose/mongoose/mongoose.c:3922
#6  0x400f3f28 in mg_mgr_poll (m=0x3ffb411c <MyNetManager+12>, timeout_ms=250) at
/home/balzer/esp/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/components/mongoose/mongoose/mongoose.c:2451
#7  0x400eb47d in OvmsNetManager::MongooseTask (this=0x3ffb4110 <MyNetManager>) at
/home/balzer/esp/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/main/./ovms_netmanager.cpp:382
#8  0x400eb4bc in MongooseRawTask (pvParameters=0x3ffb4110 <MyNetManager>) at
/home/balzer/esp/Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/main/./ovms_netmanager.cpp:370
```

**Comment by dexterbg** [comment]
I haven't seen this happen lately, guess some esp-idf update solved it.
